services:
  library-user-database:
    image: mongo:latest
    container_name: library-user-database
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    env_file:
      - .env
    volumes:
      - library-user-db-data:/data/db
    networks:
      - library-network

  library-book-database:
    image: postgres:latest
    container_name: library-book-database
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_BOOK}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_BOOK}
      - POSTGRES_DB=${POSTGRES_DB_BOOK}
    ports:
      - "5430:5432"
    volumes:
      - library-book-db-data:/var/lib/postgresql
      - ./database/book/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - library-network

  library-loan-database:
    image: postgres:latest
    container_name: library-loan-database
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_LOAN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_LOAN}
      - POSTGRES_DB=${POSTGRES_DB_LOAN}
    ports:
      - "5431:5432"
    volumes:
      - library-loan-db-data:/var/lib/postgresql
      - ./database/loan/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - library-network

  library-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: library-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - "ES_DEFAULT_SHARDS=1"
      - "ES_DEFAULT_REPLICAS=0"
    ports:
      - "9200:9200"
    volumes:
      - library-elastic-data:/usr/share/elasticsearch/data
    networks:
      - library-network

  library-kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: library-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://library-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - library-elasticsearch
    networks:
      - library-network

  library-kafka:
    image: apache/kafka:3.7.1
    container_name: library-kafka
    hostname: library-kafka
    networks:
      - library-network
    ports:
      - "9092:9092"
      - "9094:9094"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "kraft-cluster-id-1234"

      KAFKA_LISTENERS: >
        PLAINTEXT_INTERNAL://:9092,
        PLAINTEXT_EXTERNAL://:9094,
        CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT_INTERNAL://library-kafka:9092,
        PLAINTEXT_EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT_INTERNAL:PLAINTEXT,
        PLAINTEXT_EXTERNAL:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@library-kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    volumes:
      - library-kafka-data:/var/lib/kafka/data

volumes:
  library-user-db-data: {}
  library-book-db-data: {}
  library-loan-db-data: {}
  library-elastic-data: {}
  library-kafka-data: {}
networks:
  library-network:
    driver: bridge