services:
  library-user-database:
    image: mongo:latest
    container_name: library-user-database
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - library-user-db-data:/data/db
    networks:
      - library-network

  library-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: library-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - "ES_DEFAULT_SHARDS=1"
      - "ES_DEFAULT_REPLICAS=0"
    ports:
      - "9200:9200"
    volumes:
      - library-elastic-data:/usr/share/elasticsearch/data
    networks:
      - library-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - library-network

volumes:
  library-user-db-data: {}
  library-elastic-data: {}

networks:
  library-network:
    driver: bridge