server:
  port: 0
  devtools:
    add-properties: false
  profiles:
    include: dev
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
adapters:
  persistence:
    host: localhost
    port: 9200
entry-points:
  kafka:
    consumer:
      bootstrap-servers: "localhost:9094"
      group-id: "Audit-Service"
      auto-offset-reset: "latest"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    properties:
      max.poll.records: 100
      fetch.min.bytes: 500
    audit-topic: "audit-log"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    pe:
      ask:
        library: TRACE
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"