server:
  port: 0
  devtools:
    add-properties: false
  profiles:
    include: dev
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
adapters:
  persistence:
    host: localhost
    port: 5430
    database: library-book
    username: theask
    password: elAllan!!12345
    schema: public
  kafka:
    producer:
      bootstrap-servers: "localhost:9094"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    pe:
      ask:
        library: TRACE
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"